apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-stickers-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "表情包"
    rbac.authorization.halo.run/ui-permissions: '["plugin:stickers:view"]'
    rbac.authorization.halo.run/display-name: "表情包查看"
rules:
  - apiGroups: [ "storage.halo.run", "console.api.sticker.halo.run" ]
    resources: [ "stickers", "stickerGroups" ]
    verbs: [ "get", "list" ]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-stickers-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: '["role-template-stickers-view"]'
    rbac.authorization.halo.run/ui-permissions: '["plugin:stickers:manage"]'
    rbac.authorization.halo.run/module: "表情包"
    rbac.authorization.halo.run/display-name: "表情包"
rules:
  - apiGroups: [ "storage.halo.run", "console.api.sticker.halo.run" ]
    resources: [ "stickers", "stickerGroups" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
